const mongoose = require('mongoose');
const slugify = require('slugify');

// The provided MONGODB_URI from .env
const MONGODB_URI = "mongodb+srv://guru_jewellers:WnSv3foIKcq44JPQ@gurujewellers.uqvdhl9.mongodb.net/gurujewellers?retryWrites=true&w=majority&appName=gurujewellers";

// Categories obtained from DB: gold is 694d2216f616965829952858
const GOLD_CATEGORY_ID = "694d2216f616965829952858";
// From the user's product doc, they have this priceRuleId
const PRICE_RULE_ID = "69b8229c3380c69af0af2401";

// Images provided in product doc
const productImages = [
    "https://gurujewellers.s3.eu-north-1.amazonaws.com/products/f06a0c75-c8db-4ea7-87a2-d7f837dd67a0_WhatsApp Image 2025-12-29 at 9.37.00 PM (1).jpeg",
    "https://gurujewellers.s3.eu-north-1.amazonaws.com/products/0802d680-1af0-4e91-af60-7f7da5bb854a_WhatsApp Image 2025-12-29 at 9.37.00 PM.jpeg",
    "https://gurujewellers.s3.eu-north-1.amazonaws.com/products/8b7f9f45-5460-4550-bfbb-672204f5c153_WhatsApp Image 2025-12-29 at 9.36.59 PM (1).jpeg",
    "https://gurujewellers.s3.eu-north-1.amazonaws.com/products/9c89114b-1cff-4cdb-a18f-a14167742ca4_WhatsApp Image 2025-12-29 at 9.36.59 PM.jpeg",
    "https://gurujewellers.s3.eu-north-1.amazonaws.com/products/07275a5a-f933-4306-b597-ae5507ea14d6_WhatsApp Image 2025-12-29 at 9.36.58 PM (3).jpeg"
];

// Models
const Subcategory = require('./src/models/subCategory.model');
const Product = require('./src/models/product.model');

async function seed() {
    try {
        await mongoose.connect(MONGODB_URI);
        console.log("Connected to MongoDB");

        // Create 50 subcategories in hierarchy
        // Level 1: 5
        // Level 2: 15 (3 for each Level 1)
        // Level 3: 30 (2 for each Level 2)
        
        let allSubcategories = [];
        
        console.log("Creating 50 subcategories...");
        
        // Level 1
        const level1 = [];
        for (let i = 1; i <= 5; i++) {
            const sub = await new Subcategory({
                name: `Gold Sub ${i}`,
                categoryId: GOLD_CATEGORY_ID,
                parentId: null
            }).save();
            level1.push(sub);
            allSubcategories.push(sub);
        }
        
        // Level 2
        const level2 = [];
        for (let i = 0; i < level1.length; i++) {
            for (let j = 1; j <= 3; j++) {
                const sub = await new Subcategory({
                    name: `Gold L2 ${i+1}-${j}`,
                    categoryId: GOLD_CATEGORY_ID,
                    parentId: level1[i]._id
                }).save();
                level2.push(sub);
                allSubcategories.push(sub);
            }
        }
        
        // Level 3
        const level3 = [];
        for (let i = 0; i < level2.length; i++) {
            for (let j = 1; j <= 2; j++) {
                const sub = await new Subcategory({
                    name: `Gold L3 ${i+1}-${j}`,
                    categoryId: GOLD_CATEGORY_ID,
                    parentId: level2[i]._id
                }).save();
                level3.push(sub);
                allSubcategories.push(sub);
            }
        }
        
        console.log(`Created ${allSubcategories.length} subcategories.`);

        // Create 50 products
        console.log("Creating 50 products with rotated images...");
        
        for (let i = 1; i <= 50; i++) {
            const imageIndex = (i - 1) % productImages.length;
            const mainImage = productImages[imageIndex];
            
            // Randomly pick a subcategory from the 50 we just created
            const randomSubIndex = Math.floor(Math.random() * allSubcategories.length);
            const sub = allSubcategories[randomSubIndex];
            
            const productName = `Seeded Jewel ${i}`;
            // Slug is auto-generated by pre-save hook, but we can provide one
            
            await new Product({
                name: productName,
                description: `This is a beautiful seeded jewel part ${i}. Testing hierarchy and multiple images.`,
                shortDescription: `Beautiful jewel ${i}`,
                actualPrice: 1000 + (i * 100),
                weight: 5 + (i % 20),
                unit: "g",
                stock: 100,
                image: mainImage,
                images: productImages, // Put all images in the gallery
                categoryId: GOLD_CATEGORY_ID,
                subcategoryId: sub._id,
                isFeatured: true,
                tags: "New",
                isInStock: true,
                isPriceFixed: false,
                priceRuleId: PRICE_RULE_ID,
                warranty: "Life time guarantee"
            }).save();
            
            if (i % 10 === 0) console.log(`${i} products created...`);
        }

        console.log("Seeding complete!");
        process.exit(0);
    } catch (error) {
        console.error("Seeding failed:", error);
        process.exit(1);
    }
}

seed();
