const express = require("express");
const welcomeRoute = require("./welcome.route");
const adminRoute = require("./admin.route");
const categoryRoute = require("./category.route");
const festivalRoute = require("./festival.route");
const productRoute = require("./product.route");
const relationRoute = require("./relation.route");
const subcategoryRoute = require("./subcategory.route");
// const userRoute = require('./user.route');
const promoRoute = require("./promocode.route");
const cartRoute = require("./cart.route");
const wishlistRoute = require("./wishlist.route");
const orderRoute = require("./order.route");
const reviewRoute = require("./review.route");
const superAdminRoute = require("./superAdmin.route");
const socialIntegrationRoutes = require("./socialIntegration.route");
const priceRuleRoute = require("./priceRule.route");
const bannerRoute = require("./banner.route");
const grievanceRoute = require("./grievance.route");
const uploadRoute = require("./uploadRoutes");
const userRoute = require("./user.route");
const userProductRoute = require("./userProduct.route");
const addressRoute = require("./address.route");
const paymentRoute = require("./payment.route");
const curatedCollectionRoute = require("./curatedCollection.route");
const webhookRoute = require("./webhook.route");
const filterRoute = require("./filter.route");
const dashboardRoute = require("./dashboard.route");
const notificationRoute = require("./notification.route");
const instagramVideos = require("./instagramVideo.routes");
const kittyRoutes = require("./kitty.route");
const siteSettingsRoutes = require("./siteSettings.route");
const adminSiteSettingsRoutes = require("./adminSiteSettings.route");
const returnRequestRoute = require("./returnRequest.route");
const giftRoute = require("./gift.route");
const metalRoute = require("./metal.route");
const homeRoute = require("./home.route");
const router = express.Router();

// Register your routes
router.use("/", welcomeRoute);
router.use("/admin/dashboard", dashboardRoute);
router.use("/admin/notifications", notificationRoute);
router.use("/admin", adminRoute);
router.use("/superadmin", superAdminRoute);
router.use("/categories", categoryRoute);
router.use("/festivals", festivalRoute);
router.use("/products", productRoute);
router.use("/filters", filterRoute);
router.use("/relations", relationRoute);
router.use("/subcategories", subcategoryRoute);
// router.use('/user', userRoute);
router.use("/promocodes", promoRoute);
router.use("/cart", cartRoute);
router.use("/wishlist", wishlistRoute);
router.use("/order", orderRoute);
router.use("/reviews", reviewRoute);
router.use("/social", socialIntegrationRoutes);
router.use("/prices", priceRuleRoute);
router.use("/banners", bannerRoute);
router.use("/grievances", grievanceRoute);
router.use("/instagram-videos", instagramVideos);

router.use("/upload", uploadRoute);
router.use("/user/products", userProductRoute);
router.use("/user", userRoute);
router.use("/addresses", addressRoute);
router.use("/payment", paymentRoute);
router.use("/curated-collections", curatedCollectionRoute);
router.use("/kitty", kittyRoutes);
router.use("/settings", siteSettingsRoutes);
router.use("/admin/site-settings", adminSiteSettingsRoutes);
// router.use("/webhook", webhookRoute);
router.use("/returns", returnRequestRoute);
router.use("/user/gift", giftRoute);
router.use("/admin/gift", giftRoute);
router.use("/metals", metalRoute);
router.use("/homepage", homeRoute);
module.exports = router;
