const constants = {
    success: {
        welcome: "Welcome to Suno",
        otpSend: "An otp has been sent to your email",
        messsageMarkAsRead: "All messages marked as read",
        emailVerify: "Email Verify Link has been sent to your email",
        emailChangeSuccess:
            "Your email has been successfully updated. Please remember to use this new email for future communications and account logins.",
        successPhoneNumberUpdate:
            "Success! Your phone number has been updated. Keep your contact information current to stay connected with us.",
        otpSendPhone: "Otp has been sent to your Phone Number",
        otpVerify: "Otp verified successfully",
        otpEmailSend: "Otp has been sent to your email address",
        forgetPassword: "Email has been sent with password reset link",
        ResetPassword: "Password has been reset successfully",
        logout: "Logout Successfully",
        changePassword: "Your password has been changed successfully.",
        emailNameAvailable: "This Email is available.",
        defaultMessage: "Saved successfully",
        signup: "User Registered Successfully",
        BusinessSignup: "Business Registered Successfully",
        login: "User login successfully",
        logout: "User logout successfully",
        getMyProfile: "Profile retrieved successfully",
        updateProfile:
            "Your profile has been successfully updated. Thank you for keeping your information current and secure.",
        videoUpload:
            "Your video has been successfully uploaded for verification. Thank you for your submission! We'll notify you once the verification process is complete.",
        fileUpload: "File uploaded successfully",
        setpProfile: "Profile setup successfully",
        alreadyLoggedOut: "Already logged out",
        updateProfileImage: "Profile Image uploaded successfully",
        createUser: "User created successfully",
        updateUser: "User update successfully",
        userDeleted: "User Deleted successfully",
        statuschange: "Status change successfully",
        createVendor: "Vendor created successfully",
        getAllFaq: "Faqs retrieved successfully",
        getStaticData: "Static Data retrieved successfully",
        orderCreated: "Order created successfully",
        expenseAdded: "Expense added successfully",
        meterCreated: "Meter connection created successfully",
        meterUpdated: "Meter connection Updated successfully",
        meterDeleted: "Meter connection Deleted successfully",
        getMeter: "Meter connection retrieved successfully",
        sendQuery: "Query send successfully",
        getQuery: "Chat fetch list successfully",
        purchaseToken: "Token purchased successfully",
        tokenStatus: "Token status update successfully",
        transactionAdd: "Transaction Add successfully",
        walletAdd:
            "Success! Funds have been added to your account. Your balance has been updated accordingly.",
        earningAdd: "Earning add successfully",
        withdrawRequest: "Your withdrawal request has been accepted.",
        earningGet: "Earning Get successfully",
        transactionhistory: "Transaction History Retrieved Successfully",
        verifyMeter: "Meter verified successfully",
        tokenCreated: "Token created successfully",
        cardUpdate: "Card update successfully",
        cardDeleted: "Card Deleted successfully",
        cardMeter: "Card retrieved successfully",
        flightDetails: "Flight details Added successfully",
        contactus: "We Will Get Back Soon",
        addressUser: "Address retrieved successfully",
        paystackPayment: "Paystack payment successfully",
        walletAmountSuccess: "Amount added in wallet successfully",
        DailyUsageHistory: "Daily usage history data fetched successfully",
        GraphData: "Graph data fetched successfully",
        monthlyAvgUnits: "The monthly average units data fetched successfully",
        weeklyAvgUnits: "The weekly average units data fetched successfully",
        dailyAvgUnits: "The daily average units data fetched successfully",
        totalUnitUsed: "Total units used data fetched successfully",
        getAllNotification: "Notifications retrieved successfully",
        notificationRead: "You have read this notification.",

        getLastNotifcations: "Last notifications retrieved successfully",
        clearNotification: "Notifications marked as Cleared successfully",
        seenNotification: "Notifications marked as seen successfully",
        cronJobStatus: "Cron Job start successfully",
        userList: "User list fetched data successfully",
        flightbookingList: "Flight Booking list fetched data successfully",
        userDetail: "User details fetched data successfully",
        dashboardData: "Dashboard fetched data successfully",
        notificationSend: "NotificationSend send successfully",
        supportStatus: "Support data fetched successfully",
        supportDeleted: "Support Deleted successfully",
        applied: "Applied successfully",
        reviewSuccessCreate: "Your Review has been successfully submitted.",
        notificationSuccessCreate: "Notification Read Successfully ",
        getReview: "Review retrieved successfully",
        getRequest: "Requests retrieved successfully",
        createCategory: "Category created successfully",
        updateCategory: "Category update successfully",
        getPrivacyPage: "Privacy Policy retrieved successfully",
        updatePrivacyPolicy: "Privacy and Policy update successfully",
        updateTermsAndConditions: "Terms and Conditions update successfully",
        updateStatus: "Status update successfully",
        addServiceImage: "Service Images uploaded successfully",
        deleteAccount: "Your account Deleted successfully",
        deleteReason: "Reason Deleted successfully",
        deleteDraft:
            "Draft deleted successfully. It has been removed from your draft list. Thank you!",
        getQuery: "Query retrieved successfully",
        addressAdd: "Add Address successfully",
        notificationAdd: "Add Notification successfully",
        statusChangePromocode: "Status Update successfully",
        statusChangeAddress: "Status Update successfully",
        addBank: "Bank Deatils Addedd successfully",
        withdrawalBank: "Withdrawal successfully",
        getBankDetails: "Bank details retrieved successfully",
        getWalletDetail: "Wallet details retrieved successfully",
        updateBankDetails: "Bank Details Update successfully",
        deletedBankDetails: "Bank Details Deleted successfully",
        createPlan: "Plan created successfully",
        createPromocode: "Promo Code created successfully",
        sendEmail: "Email send successfully",
        createPolicyTerm: "Policy Term created successfully",
        createTermsAndConditions: "Terms and Conditions created successfully",
        createAboutus: "About Us created successfully",
        getClientReview: "Client Review retrieved successfully",
        getPolicyTerm: "Policy Term retrieved successfully",
        deletedPartner: "Partner Deleted successfully",
        sendInvitation:
            "Your invitation has been successfully sent. Thank you! We'll notify you once your invitation is accepted.",
        referInvitation: "Your invitation has been successfully refered.",
        deletemessage: "Message deleted successfully",
        allMessage: "All Message retreived successfully",
        isClear: "Clear all notification successfully",
        phonenotVerify:
            "Your Phone Number has not been verified. Please Verify your phone Number",
        addNotes: "Notes added successfully",
        draftNotes: "Notes draft retreived successfully",
        userNotes: "User Notes retreived successfully",
        invitationNotes: "Invitation retreived successfully",
        addReason: "Reason added successfully",
        addDisputeMsg:
            "You have raised a dispute on the contract. Our team will review the details and reach out to you shortly for further assistance. Thank you!!",
        endDisputeMsg:
            "Dispute successfully resolved. Contract matter settled by your help. Thank you for your cooperation.",
        reasonList: "Reason list retreived successfully",
        withdrawalList: "withdrawal List retreived successfully",
        transactionHistory: "Transaction history retrieved successfully",
        updateReason: "Reason updated successfully",
        updateNotes: "Notes updated successfully",
        addDraft:
            "Your draft has been successfully added. You can access it from your drafts for further editing or searching. Keep up the great work!",
        phoneNoChange:
            "Success! Your phone number has been updated. Keep your contact information current to stay connected with us.",
        statusChange: "Status Change successfully",
        contractEnd:
            "Contract successfully ended. Thank you for your cooperation. If you have any further inquiries or need assistance, feel free to reach out to our real time humans.",
        rejectInvitation:
            "Your decision has been noted. Thank you for your response.",
        invitationAccepted: "Congratulations! You have started your new contract.",
        videoVerified: "Video Verified successfully",
        videoUnVerified: "Video Unverified successfully",
        disputeList: "Dispute list retreived successfully",
        continueChat: "Now start Chat",
    },
    error: {
        internalServer: 'Internal Server Error',
        default: "Oops! something went wrong",
        updateFailed: "Update failed",
        optExpired: "Otp has been expired",
        inavalidOtp: "Invalid Otp.",
        alreadyVerifyOtp: "Otp already verified.",
        inavalidEmail: "Invalid email id.",
        emailAlreadyExist: "This email is already registered with us",
        myemailAlreadyExist:
            "This email is already using by your account! Please try another.",
        myPhoneAlreadyExist:
            "You have already added this phone number before. Please try another number.",
        mobileAlreadyRegistered: "This mobile number is already registered with us",
        blockUser: "Your account has been blocked. Please contact admin",
        approveUser: "Your account is not approve. Please contact admin",
        phoneNumberAlreadyExist: "This Phone number is already registered with us",
        invalidToken:
            "Someone else login on another device with your credentials. Please login again to continue",
        tokenRequried: "accessToken header must be provided",
        tokenExpired: "Link expired",
        invalidPassword: "Invalid Password",
        invalidOldPassword: "Invalid Old Password",
        sameAsOldPassword:
            "Your new password cannot be the same as your old password. Please choose a different one for improved security.",
        invalidRole: "Unauthenticated user role",
        noUserFound: " User not Found!",
        noWithdrawalFound: " No Withdraw Found!",
        emailuserAlreadyVerify: "Your Email verify already",
        noDraftNotesFound: "Draft Notes not Found!",
        noReasonFound: " Reason not Found!",
        passwordMatch: "Password and Confirm Password must be same",
        validationError: "Please add appropriate data in given field",
        noLevelUpgrade: "Problem in upgrading level",
        noProductFound: "Product may have been removed or it doesn't exist.",
        insufficientBalance: "Insufficient lifium coins",
        invalidEvent: "Event not found!",
        noInviteFound: "No Invite found!",
        noMessageFound: "No Message found!",
        tokenNotFound: "Token detail not found!",
        orderNotFound: "Order detail not found!",
        supportNotFound: "Support detail not found!",
        walletBalanceLow: "Your wallet balance is low,add money to proceed further",
        walletBalance: "Your wallet balance is zero",
        reviewAlreadyExist: "You have already submitted a review.",
        noReviewFound: " Review not Found!",
        noNotesFound: "Notes not Found!",
        noNotificationFound: " Notification not Found!",
        messageIdFound: " Message Id found successfully",
        noFoundProduct: "Product not Found!",
        favouriteAlreadyExist: "You have already add Favourite ",
        noFavouriteFound: "Favourite not Found!",
        cartAlreadyExist: "You have already add to cart ",
        noFoundQuery: "Query not Found!",
        maximumAddress: "Maximum 5 Address added",
        detailNotFound: "Details not found!",
        notificationNotFound: "Notification not found!",
        bankNotFound: "Bank account not found!",
        noFoundTemplate: "Template not Found!",
        messageNotFound: "Message not found!",
        noDocumentDetails: "No Document Details Found!",
        noVerifyId: "Please Verify your Id",
        walletNotFound: "Wallet not found!",
        emailnotVerify:
            "Your email has not been verified. We've sent a verification link to your email address. Please check your inbox and follow the instructions to verify your email.",
        incorrectLogin: "Incorrect credentials! Please log in with Google/Apple.",
        emailPhoneNotVerify:
            "Your email and Phone has not been verified. Please Verify Your Phone No and Email",
        receiverIdNotFound: "Receiver Id Not Found!",
        messageIdNotFound: "Message Id Not Found!",
        noTransactionFound: " Transaction not Found!",
    },
    status: {
        validation: "Unprocessable Entity",
        authorization: "Unauthorized",
        internalServerError: "Internal Server Error",
        badRequest: "Bad Request",
    },
};

module.exports = constants;
